name: CI Docker Citation du Jour

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: 📥 Récupération du code source
      uses: actions/checkout@v4

    - name: 🐳 Test de construction des images Docker
      run: docker compose build
