name: CI Docker Citation du Jour

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  code-quality:
    name: Lint & Tests
    runs-on: ubuntu-latest
    steps:
      - name: 📥 Récupération du code source
        uses: actions/checkout@v4

      - name: ⚙️ Configuration de Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: 📦 Installation globale des dépendances (Monorepo)
        run: npm install

      - name: 🔍 Exécution du Lint (Syntaxe)
        run: npx eslint backend/

      - name: 🧪 Exécution des Tests
        env:
          DB_USER: test
          DB_PASSWORD: test
          DB_HOST: localhost
          DB_NAME: test
        run: npm test

  docker-build:
    name: Build Docker
    needs: code-quality
    runs-on: ubuntu-latest
    steps:
      - name: 📥 Récupération du code source
        uses: actions/checkout@v4

      - name: 🐳 Test de construction des images
        run: docker compose build